
lbr_command_node:
  ros__parameters:

    id: '1' # Robot ID
    port: 30005
    KMR/ip: '172.31.1.69'

kmp_command_node:
  ros__parameters:

    id: '1' # Robot ID
    port: 30002
    KMR/ip: '172.31.1.69'